src/config/routes.rb
Rails.application.routes.draw do
  resources :excels
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/excel.rb
class Excel < ApplicationRecord
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

src/app/controllers/excels_controller.rb
class ExcelsController < ApplicationController
  before_action :set_excel, only: %i[ show edit update destroy ]

  # GET /excels or /excels.json
  def index
    @excels = Excel.all

    # 以下、追記
    respond_to do |format|
      format.html
      format.xlsx do
        # ファイル名をここで指定する（動的にファイル名を変更できる）
        response.headers['Content-Disposition'] = "attachment; filename=#{Date.today}.xlsx"
      end
    end
  end

  # GET /excels/1 or /excels/1.json
  def show
  end

  # GET /excels/new
  def new
    @excel = Excel.new
  end

  # GET /excels/1/edit
  def edit
  end

  # POST /excels or /excels.json
  def create
    @excel = Excel.new(excel_params)

    respond_to do |format|
      if @excel.save
        format.html { redirect_to @excel, notice: "Excel was successfully created." }
        format.json { render :show, status: :created, location: @excel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @excel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excels/1 or /excels/1.json
  def update
    respond_to do |format|
      if @excel.update(excel_params)
        format.html { redirect_to @excel, notice: "Excel was successfully updated." }
        format.json { render :show, status: :ok, location: @excel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @excel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excels/1 or /excels/1.json
  def destroy
    @excel.destroy
    respond_to do |format|
      format.html { redirect_to excels_url, notice: "Excel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excel
      @excel = Excel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def excel_params
      params.require(:excel).permit(:day, :name, :place, :title)
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/excels_helper.rb
module ExcelsHelper
end

src/app/views/excels/_form.html.erb
<%= form_with(model: excel) do |form| %>
  <% if excel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(excel.errors.count, "error") %> prohibited this excel from being saved:</h2>

      <ul>
        <% excel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/excels/edit.html.erb
<h1>Editing Excel</h1>

<%= render 'form', excel: @excel %>

<%= link_to 'Show', @excel %> |
<%= link_to 'Back', excels_path %>

src/app/views/excels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>車だしの記録</h1>

<!-- 以下の1行を追記 -->
<%= link_to "Excel出力", excels_path(@excels, format: :xlsx) %>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Name</th>
      <th>Place</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @excels.each do |excel| %>
      <tr>
        <td><%= excel.day %></td>
        <td><%= excel.name %></td>
        <td><%= excel.place %></td>
        <td><%= excel.title %></td>
        <td><%= link_to 'Show', excel %></td>
        <td><%= link_to 'Edit', edit_excel_path(excel) %></td>
        <td><%= link_to 'Destroy', excel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excel', new_excel_path %>

src/app/views/excels/new.html.erb
<h1>New Excel</h1>

<%= render 'form', excel: @excel %>

<%= link_to 'Back', excels_path %>

src/app/views/excels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @excel.day %>
</p>

<p>
  <strong>Name:</strong>
  <%= @excel.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @excel.place %>
</p>

<p>
  <strong>Title:</strong>
  <%= @excel.title %>
</p>

<%= link_to 'Edit', edit_excel_path(@excel) %> |
<%= link_to 'Back', excels_path %>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>